### ISSUE TITLE
QoS DSCP value not matching one of supported classes

### ISSUE THREAD

**Issue by rmrf** [uber/arachne#19]
```json
{"level":"error","ts":1496825431.2770894,"msg":"QoS DSCP value not matching one of supported classes","PID":1124,"hostname":"hostname1","service_name":"arachne","DSCP_value":20,"supported_classes":"[0 4 40 56 72 88 104 120 160 192 224]" }
```

my centos 7 hosts encounter above error, any way to make it work?

**Comment by rmrf** [comment]
btw,  qos is disabled in my configuration: `    "qos": "disabled",`

**Comment by henridevieux** [comment]
This message is likely because of one of the following:
- The agent is incorrectly trying to process packets not destined for it
- Something in your network between two Arachne agents is altering the DSCP value in the IP header. 

Can you run tcpdump and see if packets being sent from one arachne agent are arriving to the other agent unchanged?

**Comment by rmrf** [comment]
Thanks @henridevieux, I think the cloud vendor did modify the packets, one clue is even I didn't start 443 port on my remote target cloud host, but from our client side tcpdump output, I  can see the packet return from it's 443 port...

might be some firewall kind of sensor before my cloud host, making this change and response. 

I'm using arachne on serveral cloud vendors, only one have this kind of issue. 

so there is no way to bypass this, right?

**Comment by henridevieux** [comment]
If something in the network that sits between your Arachne agents is modifying the IP headers, then unfortunately no, there won't be a way around it. 

I do think, however, that this should be a warning instead of an error. You're not testing QoS anyway so there is no reason to be seeing an error for an invalid DSCP value. 

I'll submit a diff to change this to a warning instead.

**Comment by henridevieux** [comment]
#20

**Comment by rmrf** [comment]
Thank you @henridevieux
